[book]
authors = ["Mingxian Su, Keyang Hu"]
language = "cn"
multilingual = false
src = "src"
title = "AxVisor Book"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/arceos-hypervisor/doc"
additional-css = ["src/assets/css/custom.css", "theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]

[output.html.playpen]
editable = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[preprocessor.pagetoc]
