name: github pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  # Update the language picker in index.hbs to link new languages.
  LANGUAGES: en
  default-branch: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Install Gettext
        run: |
          sudo apt update
          sudo apt install gettext

      - name: Setup mdbook-pagetoc
        run: cargo install mdbook-pagetoc

      - name: Setup embedify
        run: cargo install mdbook-embedify

      - name: Setup mdbook-i18n-helpers
        run: cargo install mdbook-i18n-helpers

      # - name: Setup i18n-report
      #   run: cargo install i18n-report

      - name: Build docs
        run: mdbook build

      - name: Build all translations
        run: |
          for po_lang in ${{ env.LANGUAGES }}; do
              MDBOOK_BOOK__LANGUAGE=$po_lang mdbook build -d book/$po_lang
          done

      # - name: Build synced translation report
      #   run: |
      #     cp -r po synced-po
      #     MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot", "granularity": 0}}' mdbook build -d synced-po
      #     for file in synced-po/*.po; do msgmerge --update $file synced-po/messages.pot ; done
      #     i18n-report report book/html/synced-translation-report.html synced-po/*.po

      # - name: Setup Pages
      #   uses: actions/configure-pages@v5

      - name: Deploy to Github Pages
        if: ${{ github.ref == env.default-branch }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          single-commit: true
          branch: gh-pages
          folder: book