name: github pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      default-branch: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      - name: Setup mdbook mermaid env
        run: cargo install mdbook-mermaid
      - name: preprocess mdbook mermaid graph
        run: mdbook-mermaid install
      - name: Build mdbook
        run: mdbook build
      - name: Deploy to Github Pages
        if: ${{ github.ref == env.default-branch }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          single-commit: true
          branch: gh-pages
          folder: book